### ISSUE TITLE
Getting "Bad owner or permissions" error in ssh (Windows)

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#12]
Hi,

When I do ssh -T git@github.com in windows machine, it gives me following error:

Bad owner or permissions on C:\\Users\\Pratibha/.ssh/config

Any help?

Thanks

**Comment by satyapalvadi** [comment]
@hemantbajpai Did you update the .ssh/config file with your ssh private key file location?

**Comment by hemantbajpai** [comment]
that also did not work.

**Comment by DoryAzar** [comment]
just out of curiosity could you try to use elevate before the ssh: 'elevate ssh -T git@github.com`

**Comment by Trong09** [comment]
I am on the same boat, 
C:\Users\Trong\.ssh 
λ ssh -T git@github.com 
Bad owner or permissions on C:\\Users\\Trong/.ssh/config

**Comment by susanBuck** [comment]
Can you run the list command `ls -la` in your .ssh directory so we can see the permissions?

To compare and contrast, here's what the details look like on my Windows machine:

```
C:\Users\Susan\.ssh
λ ls -la
total 40
drwxr-xr-x 1 Susan 197121    0 Sep 12 09:06 .
drwxr-xr-x 1 Susan 197121    0 Sep 12 09:08 ..
-rw-r--r-- 1 Susan 197121   24 Sep 12 09:06 config
-rw-r--r-- 1 Susan 197121 1675 Sep 12 09:02 dwa
-rw-r--r-- 1 Susan 197121  404 Sep 12 09:02 dwa.pub
-rw-r--r-- 1 Susan 197121 1675 Feb  2  2017 id_rsa
-rw-r--r-- 1 Susan 197121  407 Feb  2  2017 id_rsa.pub
-rw-r--r-- 1 Susan 197121 1376 Mar  8  2018 known_hosts
-rw-r--r-- 1 Susan 197121  477 Nov 28  2017 putty
-rw-r--r-- 1 Susan 197121 1460 Nov 28  2017 putty.ppk
```

The other thing that sticks out to me is the mixing of back and forward slashes in paths like  `C:\Users\Pratibha/.ssh/config` and `C:\Users\Trong/.ssh/config`.  Is this what your paths are actually reading, or is that just a error in re-typing?

**Comment by susanBuck** [comment]
I was just reviewing the notes, and realize the mixing of slashes may come from how I'm instructing you to edit/create that config file. 

The notes say to do this:
```
nano ~/.ssh/config
```

I forgot to include the Windows equivalent which is slightly different:

```
nano %home%/.ssh/config
```

Apologies for that. Correcting now. This bit of the notes is a new addition for this semester (previously we used default key names and thus we didn't have to edit the config file).

**Comment by susanBuck** [comment]
Update: I've clarified the notes that show how to edit the SSH config file so that it's operating system independent.
Ref: https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/github-setup.md#ssh-config-file

The interesting thing is the path you're adding to config is a mac/unix style path (`IdentityFile ~/.ssh/dwa`), but it still works. I'm guessing because the SSH program is unix based.

Hopefully the above helps resolve this issue, but if not, let us know and we'll keep troubleshooting!

**Comment by fpizzuta** [comment]
I fixed the permissions issue by going into windows explorer and giving myself full rights on all the files etc in the .ssh folder.

**Comment by calivine** [comment]
I encountered the same issue testing the Github connection on Cmdr (Windows 10). 
`Bad owner or permissions on C:\\Users\\calog/.ssh/config`
I had success connecting when I tried using the Git Bash command line interface. I will try to change my permissions for the .ssh folder as well.

**Comment by Trong09** [comment]
I tried to change permission and it didn't work. However, I was able to get it to work with git bash command line. Thanks


________________________________

**Comment by susanBuck** [comment]
For those of you still getting permission errors, I'd be curious to see what your permissions are set to. Can someone share their output of `ls -la` from within `%home%/.ssh` ?

**Comment by Trong09** [comment]
C:\Users\Trong\.ssh
λ ls -la
total 23
drwxr-xr-x 1 Trong 197609    0 Sep 16 11:08 .
drwxr-xr-x 1 Trong 197609    0 Sep 16 11:10 ..
-rw-r--r-- 1 Trong 197609   29 Sep 16 10:36 config
-rw-r--r-- 1 Trong 197609 1679 Sep 16 07:06 dwa
-rw-r--r-- 1 Trong 197609  410 Sep 16 07:06 dwa.pub
-rw-r--r-- 1 Trong 197609  407 Sep 16 11:08 known_hosts



________________________________

**Comment by calivine** [comment]
This is my output after I tried changing all the permissions of the .ssh contents:
`C:\Users\calog\.ssh`
`λ ls -la`
`total 26`
`drwxr-xr-x 1 calog 197609    0 Sep 13 22:09 .`
`drwxr-xr-x 1 calog 197609    0 Sep 14 16:30 ..`
`-rw-r--r-- 1 calog 197609   24 Sep 16 10:58 config`
`-rw-r--r-- 1 calog 197609 1679 Sep 13 21:55 dwa`
`-rw-r--r-- 1 calog 197609  405 Sep 13 21:55 dwa.pub`
`-rw-r--r-- 1 calog 197609  978 Sep 14 19:33 known_hosts`

**Comment by susanBuck** [comment]
Thanks @Trong09 and @calivine! That's helpful to see. The permissions look fine. 
I'm going to see if I can recreate the issue on my end on another Windows machine and report back on what I find.

**Comment by DoryAzar** [comment]
@calivine, @Trong09, @susanBuck,

I am not using a Windows machine, however I did experience the same problem on my work computer (Sierra OS). Some OS do not like that the config file or even the keys to be writable - which seems to be the case of your permissions right now. At the very least, Make sure that your config file is mod 600 NOT 644. If that doesn’t work then try to change ur key files to mod 600 as well. I am not sure why that is but it did seem to
solve it for me on Sierra at work.

**Comment by susanBuck** [comment]
[This is a useful post from ServerFault on the issue](https://serverfault.com/questions/253313/ssh-returns-bad-owner-or-permissions-on-ssh-config), although, with some slightly conflicting information. Some people say to use `600`, others `644`.

To be clear, here's the difference between the two:

### 600
<img width="458" alt="2018-09-17_1057" src="https://user-images.githubusercontent.com/237711/45631223-73fb1500-ba68-11e8-859f-e317cca6f43f.png">

### 644
<img width="455" alt="2018-09-17_1057-1" src="https://user-images.githubusercontent.com/237711/45631262-88d7a880-ba68-11e8-9da3-5b8a53f78619.png">

(Aside: If you're unfamiliar with file permissions, [here's a supplemental note set I have on the topic](https://github.com/susanBuck/dwa15-fall2018/blob/master/command-line/permissions.md))

One comment in the above-mentioned ServerFault post cited this from the SSH man page:

>> Because of the potential for abuse, this file must have strict permissions: read/write for the user, and not writable by others. It may be group-writable provided that the group in question contains only the user.

To me, that suggests that either 600 or 644 should work, since neither allows the writable permission for others. 

For reference, all of the examples we've seen in this thread so far are using `644`:
```
# @Trong09's
-rw-r--r-- 1 Trong 197609   29 Sep 16 10:36 config

# @calivine's
-rw-r--r-- 1 calog 197609   24 Sep 16 10:58 config

# @susanBuck's
-rw-r--r-- 1 Susan 197121   24 Sep 12 09:06 config
```

## Ownership
Further research lead me to this post [Bad owner or permissions on C:\\Users\\USER/.ssh/config #1763](https://github.com/cmderdev/cmder/issues/1763) which suggests that the SSH `config` file may be inheriting permissions it shouldn't, making it writable by others.

The suggested fix there is to change a security inheritance property on the SSH `config` file.

To do this, locate the file in your file browser and right click on it to find the *Properties* option.

From there, click the following:
*Security -> Advanced -> Disable Inheritance -> Remove all inherited permissions from this object*

## Bypassing the SSH config file
If all else fails, and you're still getting the `Bad owner or permissions` error on your SSH config file, you can bypass the config file by directly specifying the key to use when issuing a SSH key.

This is done by including the `-i` (identity) flag.

For example, here's how I'd test my SSH connection to Github using my `dwa` private key:
```
ssh -T -i %home%/.ssh/dwa git@github.com
```

Similarly, here's how i'd SSH into my DigitalOcean server (be sure to swap in your own IP address when testing this):
```
ssh -i %home%/.ssh/dwa root@159.65.236.201
```

**Comment by calivine** [comment]
Changing permissions to `600` worked for me. Thank you!

**Comment by susanBuck** [comment]
Closing this issue as I believe we came to a resolution. If anyone else is still having problems with this, feel free to start a new thread or continue the discussion on this one.

**Comment by ClericPy** [comment]
### [Solved]

The ways above to update file permissions on windows is not work for me.

But git-bash will not raise the permissions error.

So, I checked ssh version and found that, 

```
λ where ssh
C:\Windows\System32\OpenSSH\ssh.exe
C:\Program Files\Git\usr\bin\ssh.exe

λ C:\Windows\System32\OpenSSH\ssh.exe -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

λ "C:\Program Files\Git\usr\bin\ssh.exe" -V
OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019

```
Obviously, 
git-bash use the 8.0 version
cmder use the 7.7 version

So, I tried to change the svn_ssh option, but failed.

Then I found the system path env is 
![image](https://user-images.githubusercontent.com/7133852/66182580-3df6f600-e6a8-11e9-893e-ff134cf55bfe.png)
So? change the order
![image](https://user-images.githubusercontent.com/7133852/66182592-4b13e500-e6a8-11e9-991d-f5620913b71a.png)

Success.
```
λ ssh aliyun
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-13-generic x86_64)
```

Maybe this solution will help you.

**Comment by LoveSponge** [comment]
for anyone that runs into this problem, if you happen to be using SCOOP (windows package manager like chocolatey) with powershell or pwsh, go ahead, remove that piece of rubbish that windows optimistically called 'openssh feature for windows' and
`scoop install openssh`
make sure that your `ssh -V` returns something like:
`OpenSSH_8.2p1, OpenSSL 1.1.1e  17 Mar 2020`
*AND NOT:*
`OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5`

if it is, you need to go to settings > search 'optional features' > uninstall openssh client & server.

Happy days.
